apiVersion: v1
kind: Pod
metadata:
  name: nc-pod 
  labels:
    app: nc-pod
spec:
  nodeSelector:
    kubernetes.io/hostname: work002
  hostNetwork: true
  containers:
  - name: nc-pod
    image: kaiyfan/test
    ports:
    - containerPort: 9000
      protocol: UDP
    - containerPort: 8081
    - containerPort: 1234
    command: ["nc","-l","-k", "-p", "1234"]
